Imports MaterialSkin
Public Class FormDificultades
    Private Sub FormDificultades_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Dim SkinManager As MaterialSkinManager = MaterialSkinManager.Instance
        SkinManager.AddFormToManage(Me)
        SkinManager.Theme = MaterialSkinManager.Themes.DARK
        SkinManager.ColorScheme = New ColorScheme(Primary.BlueGrey800, Primary.BlueGrey900, Primary.BlueGrey500, Accent.LightBlue200, TextShade.WHITE)
    End Sub

    Private Sub MaterialRaisedButton1_Click(sender As Object, e As EventArgs) Handles MaterialRaisedButton1.Click
        DificultadElegida = 1
        DificultadBajaNivel = 1
        DificultadMediaNivel = 0
        DificultadAltaNivel = 0
        Score = 0
        FormJugar.LabelContador.Text = " 0 "
        ContInfo = 0
        If DificultadElegida = 1 Then
            If DificultadBajaNivel = 1 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
            ElseIf DificultadBajaNivel = 2 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
            ElseIf DificultadBajaNivel = 3 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadBajaNivel = 4 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadBajaNivel = 5 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadBajaNivel = 6 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadBajaNivel = 7 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadBajaNivel = 8 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadBajaNivel = 9 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
            ElseIf DificultadBajaNivel = 10 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
            End If
        ElseIf DificultadElegida = 2 Then
            If DificultadMediaNivel = 1 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadMediaNivel = 2 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadMediaNivel = 3 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadMediaNivel = 4 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadMediaNivel = 5 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadMediaNivel = 6 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadMediaNivel = 7 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
            ElseIf DificultadMediaNivel = 8 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
            ElseIf DificultadMediaNivel = 9 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
            ElseIf DificultadMediaNivel = 10 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
            End If
        ElseIf DificultadElegida = 3 Then
            If DificultadAltaNivel = 1 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadAltaNivel = 2 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadAltaNivel = 3 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadAltaNivel = 4 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
            ElseIf DificultadAltaNivel = 5 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
            ElseIf DificultadAltaNivel = 6 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
            ElseIf DificultadAltaNivel = 7 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
            ElseIf DificultadAltaNivel = 8 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
                FormJugar.PictureBoxObjetivo11.Show()
            ElseIf DificultadAltaNivel = 9 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
                FormJugar.PictureBoxObjetivo11.Show()
                FormJugar.PictureBoxObjetivo12.Show()
            ElseIf DificultadAltaNivel = 10 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
                FormJugar.PictureBoxObjetivo11.Show()
                FormJugar.PictureBoxObjetivo12.Show()
                FormJugar.PictureBoxObjetivo13.Show()
            End If
        End If
        FormJugar.Show()
        FormInicio.Hide()
        Close()
    End Sub

    Private Sub MaterialRaisedButton2_Click(sender As Object, e As EventArgs) Handles MaterialRaisedButton2.Click
        DificultadElegida = 2
        DificultadBajaNivel = 0
        DificultadMediaNivel = 1
        DificultadAltaNivel = 0
        Score = 0
        FormJugar.LabelContador.Text = " 0 "
        ContInfo = 0
        If DificultadElegida = 1 Then
            If DificultadBajaNivel = 1 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
            ElseIf DificultadBajaNivel = 2 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
            ElseIf DificultadBajaNivel = 3 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadBajaNivel = 4 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadBajaNivel = 5 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadBajaNivel = 6 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadBajaNivel = 7 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadBajaNivel = 8 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadBajaNivel = 9 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
            ElseIf DificultadBajaNivel = 10 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
            End If
        ElseIf DificultadElegida = 2 Then
            If DificultadMediaNivel = 1 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadMediaNivel = 2 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadMediaNivel = 3 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadMediaNivel = 4 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadMediaNivel = 5 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadMediaNivel = 6 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadMediaNivel = 7 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
            ElseIf DificultadMediaNivel = 8 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
            ElseIf DificultadMediaNivel = 9 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
            ElseIf DificultadMediaNivel = 10 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
            End If
        ElseIf DificultadElegida = 3 Then
            If DificultadAltaNivel = 1 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadAltaNivel = 2 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadAltaNivel = 3 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadAltaNivel = 4 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
            ElseIf DificultadAltaNivel = 5 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
            ElseIf DificultadAltaNivel = 6 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
            ElseIf DificultadAltaNivel = 7 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
            ElseIf DificultadAltaNivel = 8 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
                FormJugar.PictureBoxObjetivo11.Show()
            ElseIf DificultadAltaNivel = 9 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
                FormJugar.PictureBoxObjetivo11.Show()
                FormJugar.PictureBoxObjetivo12.Show()
            ElseIf DificultadAltaNivel = 10 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
                FormJugar.PictureBoxObjetivo11.Show()
                FormJugar.PictureBoxObjetivo12.Show()
                FormJugar.PictureBoxObjetivo13.Show()
            End If
        End If
        FormJugar.Show()
        FormInicio.Hide()
        Close()
    End Sub

    Private Sub MaterialRaisedButton3_Click(sender As Object, e As EventArgs) Handles MaterialRaisedButton3.Click
        DificultadElegida = 3
        DificultadBajaNivel = 0
        DificultadMediaNivel = 0
        DificultadAltaNivel = 1
        Score = 0
        FormJugar.LabelContador.Text = " 0 "
        ContInfo = 0
        If DificultadElegida = 1 Then
            If DificultadBajaNivel = 1 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
            ElseIf DificultadBajaNivel = 2 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
            ElseIf DificultadBajaNivel = 3 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadBajaNivel = 4 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadBajaNivel = 5 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadBajaNivel = 6 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadBajaNivel = 7 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadBajaNivel = 8 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadBajaNivel = 9 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
            ElseIf DificultadBajaNivel = 10 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
            End If
        ElseIf DificultadElegida = 2 Then
            If DificultadMediaNivel = 1 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadMediaNivel = 2 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadMediaNivel = 3 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadMediaNivel = 4 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadMediaNivel = 5 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadMediaNivel = 6 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadMediaNivel = 7 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
            ElseIf DificultadMediaNivel = 8 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
            ElseIf DificultadMediaNivel = 9 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
            ElseIf DificultadMediaNivel = 10 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
            End If
        ElseIf DificultadElegida = 3 Then
            If DificultadAltaNivel = 1 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
            ElseIf DificultadAltaNivel = 2 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
            ElseIf DificultadAltaNivel = 3 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
            ElseIf DificultadAltaNivel = 4 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
            ElseIf DificultadAltaNivel = 5 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
            ElseIf DificultadAltaNivel = 6 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
            ElseIf DificultadAltaNivel = 7 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
            ElseIf DificultadAltaNivel = 8 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
                FormJugar.PictureBoxObjetivo11.Show()
            ElseIf DificultadAltaNivel = 9 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
                FormJugar.PictureBoxObjetivo11.Show()
                FormJugar.PictureBoxObjetivo12.Show()
            ElseIf DificultadAltaNivel = 10 Then
                FormJugar.PictureBoxObjetivo1.Show()
                FormJugar.PictureBoxObjetivo2.Show()
                FormJugar.PictureBoxObjetivo3.Show()
                FormJugar.PictureBoxObjetivo4.Show()
                FormJugar.PictureBoxObjetivo5.Show()
                FormJugar.PictureBoxObjetivo6.Show()
                FormJugar.PictureBoxObjetivo7.Show()
                FormJugar.PictureBoxObjetivo8.Show()
                FormJugar.PictureBoxObjetivo9.Show()
                FormJugar.PictureBoxObjetivo10.Show()
                FormJugar.PictureBoxObjetivo11.Show()
                FormJugar.PictureBoxObjetivo12.Show()
                FormJugar.PictureBoxObjetivo13.Show()
            End If
        End If
        FormJugar.Show()
        FormInicio.Hide()
        Close()
    End Sub
End Class